### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by huubl** [zirkeldesign/sage-blade-icons#1]
Hi,

How to use this with Sage 10?

**Comment by dsturm** [comment]
Hej @huubl,

better late than never, right 😉 As I guess from your fork, you might already have an answer to your question. But for reference sake:

This package is just a tiny wrapper to provide some of the mandatory (laravel) helper methods. Therefor you should require it in your [Sage 10 theme](https://github.com/roots/sage) - and finally require one of the [numerous icon packages](https://github.com/blade-ui-kit/blade-icons#icon-packages).

After this you should be able to use a package-depended [Blade component](https://laravel.com/docs/8.x/blade#components) to include your icon in the Blade views. I.e.

```blade
<x-heroicon-o-adjustments class="w-6 h-6 text-gray-500"/>
```

**Comment by minemindmedia** [comment]
Hi @dsturm - Thanks for this package! I followed your instructions in sage 10 but I get the following:

`Unable to locate a class or view for component [heroicon-o-adjustments]`

**Comment by dsturm** [comment]
Hi @minemindmedia,

which version of roots/sage do you use? I must admit, I didn't update / follow to the latest official release of sage 10.
Nonetheless, I was able to try it now with a clean install of the latest `v10.1.0` and got it working. 

Did you require the [blade-ui-kit/blade-heroicons](https://github.com/blade-ui-kit/blade-heroicons) package?

```
composer require blade-ui-kit/blade-heroicons
# Optional, clear cache
wp acorn view:clear
```

**Comment by minemindmedia** [comment]
Hi @dsturm thank you for your response! I required your package and the blade-hericons package with Sage 10 composer, is that correct?

I am using the latest Sage 10 release that came out on the first of the month.

```  "require": {
    "php": "^7.4|^8.0",
    "blade-ui-kit/blade-heroicons": "^1.3",
    "log1x/acf-composer": "^2.0",
    "log1x/navi": "^2.0",
    "log1x/poet": "^2.0",
    "log1x/sage-directives": "^1.1",
    "log1x/sage-html-forms": "^1.0",
    "zirkeldesign/sage-blade-icons": "^0.1.2"
  },
```

I cleared cache as you suggested and cleared yarn cache and rebuilt but still no cigar...

`Unable to locate a class or view for component [heroicon-o-adjustments]. `

**Comment by minemindmedia** [comment]
Without using this package, here's how I got this working with Sage 10:

If you’re looking to get Blade UI Kit icons setup within Sage 10 here is the process I took.

via Sage theme: composer require blade-ui-kit/blade-icons

Choose any additional icon sets you may want to include. In this cased I chose heroicons:


[GitHub](https://github.com/blade-ui-kit/blade-icons)

[GitHub - blade-ui-kit/blade-icons: A package to easily make use of SVG icons...](https://github.com/blade-ui-kit/blade-icons)
A package to easily make use of SVG icons in your Laravel Blade views. - GitHub - blade-ui-kit/blade-icons: A package to easily make use of SVG icons in your Laravel Blade views.

via Sage theme: composer require blade-ui-kit/blade-heroicons

Manually add to your providers:
BladeUI\Icons\FactoryServiceProvider::class,

Run wp acorn vendor:publish

Which provider or tag's files would you like to publish?:
  [0 ] Publish files from all providers and tags listed below
  [1 ] Provider: BladeUI\Heroicons\BladeHeroiconsServiceProvider
  [2 ] Provider: BladeUI\Icons\BladeIconsServiceProvider
  [3 ] Provider: Log1x\AcfComposer\Providers\AcfComposerServiceProvider
  [4 ] Provider: Log1x\Poet\PoetServiceProvider
  [5 ] Provider: Roots\Acorn\Providers\AcornServiceProvider
  [6 ] Tag: acorn
  [7 ] Tag: blade-heroicons
  [8 ] Tag: blade-heroicons-config
  [9 ] Tag: blade-icons
  [10] Tag: config
 > 0
Include in your blade template:
<x-heroicon-o-adjustments class="w-6 h-6 text-gray-500"/>
